version: 2
jobs:
  build:
    working_directory: ~/seb_elink
    docker:     
      # ruby:2-node
      - image: circleci/ruby@sha256:382aa3816e4a1447f56dfa5c70751a727eb276bb0d1617f1989e3ca28bb251f5
      
    steps:
      - checkout
      
      - run: gem install bundler -v 1.16.0 --no-doc      

      - restore_cache:
         key: seb_elink-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
         key: seb_elink-v1-{{ checksum "Gemfile.lock" }}
         paths:
           - vendor/bundle      

      - run: bundle exec rspec
